# Generated by Django 2.1.2 on 2018-11-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.s3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_photo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uuid_cover', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=helpers.s3.upload_image_with_custom_uuid('uuid_photo'), verbose_name='photo')),
                ('cover_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=helpers.s3.upload_image_with_custom_uuid('uuid_cover'), verbose_name='photo')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='zip code')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('discord_client_id', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
