# Generated by Django 2.1.2 on 2018-11-02 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bind', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discord_client_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discord_account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discord_account', to='discord_bind.DiscordUser'),
            preserve_default=False,
        ),
    ]
