# Generated by Django 2.1.2 on 2018-11-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181102_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discord_account',
        ),
    ]
